name: Bug report
description: Create a bug report for the "Snapdrop for Android" app.
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        Welcome! Thanks for taking the time to submit a bug report.

  - type: input
    id: version
    attributes:
      label: App version
      description: What version of "Snapdrop for Android" are you using? The version can be found as the last entery inside the Settings of the app.
    validations:
      required: true

  - type: dropdown
    id: android_version
    attributes:
      label: Android version
      multiple: false
      description: What version of Android are you running? This can usually be found in your device's settings in the "About" section.
      options:
        - newer
        - 12
        - 11
        - 10
        - 9
        - 8.1
        - 8.0
        - 7.1
        - 7.0
        - 6
        - 5.1
        - 5.0
        - I don't know
    validations:
      required: true

  - type: textarea
    id: bug_description
    attributes:
      label: Describe the bug
      description: Write a clear and concise description of the bug.
      placeholder: What went wrong? 
    validations:
      required: true

  - type: textarea
    id: bug_steps
    attributes:
      label: Steps to reproduce the bug
      description: |
        A clear and concise description of what the bug is. Bugs that are not reproducible cannot be investigated.
      placeholder: |
        Steps to reproduce the bug (e.g.):
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
      
  - type: textarea
    id: bug_crash
    attributes:
      label: Stacktrace
      description: |
        Is this bug a crash? If yes, please attach a log...
      placeholder: |
        You can create a log via `Settings > Debug Log`
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots and additional context
      description: |
        If applicable, add screenshots to help explain your problem. You can also use this section to write any further context about the problem here.
      placeholder: |
        Drag the screenshot files here to attach them.
    validations:
      required: false
